packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
  "eslint-config-next@*":
    dependencies:
      "next": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
