packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-webpack5": "*"
      "@babel/core": "*"
      "react": "*"
      "react-dom": "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      "react-dom": "*"
  eslint-config-next@*:
    dependencies:
      next: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
